---

node.name: es01
discovery.type: single-node

cluster.name: cluster-es
network.host: 0.0.0.0

xpack.license.self_generated.type: basic
bootstrap.memory_lock: true
xpack.security.enabled: true
#xpack.security.http.ssl.enabled: true
#xpack.security.http.ssl.key: certs/es01/es01.key
#xpack.security.http.ssl.certificate: certs/es01/es01.crt
#xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
#xpack.security.transport.ssl.enabled: true
#xpack.security.transport.ssl.key: certs/es01/es01.key
#xpack.security.transport.ssl.certificate: certs/es01/es01.crt
#xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
#xpack.security.transport.ssl.verification_mode: certificate
