# ========================= Prelude SIEM Configuration =========================
#
# This file is a part of the Prelude SIEM configurations files.
# Purpose:  Tune the main and sub menus.
#
# ------------------------------------ Menu ------------------------------------
#
# Specify the section order in the upper menu:
#   - All the icons available are here (v4.5): http://fontawesome.io/icons/
#
- name: ALERT
  icon: exclamation-triangle
  categories:
      - sections:
            - name: Alerts
              expand: true
              tabs:
                  - Alerts
                  - Aggregated alerts
- name: ANALYSE
  icon: bar-chart
  categories:
      - sections:
            - name: Statistics
              expand: true
              tabs:
                  - Alerts
- name: ARCHIVE
  icon: database
  categories:
      - name: Events
        sections:
            - name: Logs
              tabs:
                  - Logs
                  - Aggregated logs
- name: ADMIN
  icon: sliders
  categories:
      - sections:
            - name: Access control
              expand: true
              tabs:
                  - Users
                  - Groups
            - name: Configuration
              tabs:
                  - Scheduling
            - name: Preferences
              expand: true
              tabs:
                  - My account
                  - Filters
- icon: question
  default: true
  categories:
      - sections:
            - name: Apps
              tabs:
                  - Apps
